# Generated by Django 2.0.3 on 2018-03-31 19:45

from django.db import migrations

def create_data(apps, schema_editor):
    Boat = apps.get_model('apps', 'Boat')
    Boat(plate_number="Boat 001", boat_type="Boat Type 001",  description= "Boat 001 description").save()
    Boat(plate_number="Boat 002", boat_type="Boat Type 002",  description= "Boat 002 description").save()
    Boat(plate_number="Boat 003", boat_type="Boat Type 003",  description= "Boat 003 description").save()
    Boat(plate_number="Boat 004", boat_type="Boat Type 004",  description= "Boat 004 description").save()
    Boat(plate_number="Boat 005", boat_type="Boat Type 005",  description= "Boat 005 description").save()
    Boat(plate_number="Boat 006", boat_type="Boat Type 006",  description= "Boat 006 description").save()
    Boat(plate_number="Boat 007", boat_type="Boat Type 007",  description= "Boat 007 description").save()
    Boat(plate_number="Boat 008", boat_type="Boat Type 008",  description= "Boat 008 description").save()
    Boat(plate_number="Boat 009", boat_type="Boat Type 009",  description= "Boat 009 description").save()
    Boat(plate_number="Boat 0010", boat_type="Boat Type 0010",  description= "Boat 0010 description").save()
    Boat(plate_number="Boat 0011", boat_type="Boat Type 0011",  description= "Boat 0011 description").save()
    
    Guide = apps.get_model('apps', 'Guide')
    Guide(first_name="Guide 001", last_name="Guide LastName 001",  description= "Guide 001 description").save()
    Guide(first_name="Guide 002", last_name="Guide LastName 002",  description= "Guide 002 description").save()
    Guide(first_name="Guide 003", last_name="Guide LastName 003",  description= "Guide 003 description").save()
    Guide(first_name="Guide 004", last_name="Guide LastName 004",  description= "Guide 004 description").save()
    Guide(first_name="Guide 005", last_name="Guide LastName 005",  description= "Guide 005 description").save()
    Guide(first_name="Guide 006", last_name="Guide LastName 006",  description= "Guide 006 description").save()
    Guide(first_name="Guide 007", last_name="Guide LastName 007",  description= "Guide 007 description").save()
    Guide(first_name="Guide 008", last_name="Guide LastName 008",  description= "Guide 008 description").save()
    Guide(first_name="Guide 009", last_name="Guide LastName 009",  description= "Guide 009 description").save()
    Guide(first_name="Guide 0010", last_name="Guide LastName 0010",  description= "Guide 0010 description").save()
    Guide(first_name="Guide 0011", last_name="Guide LastName 0011",  description= "Guide 0011 description").save()
    
    SwimLane = apps.get_model('apps', 'SwimLanes')
    SwimLane(name="Docked",   description= "Docked").save()
    SwimLane(name="Outbound to Sea",   description= "Outbound to Sea").save()
    SwimLane(name="Inbound to Harbor",   description= "Inbound to Harbor").save()
    SwimLane(name="Maintenance",   description= "Maintenance").save()
class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
