# Generated by Django 2.0.3 on 2018-03-31 19:45

from django.db import migrations
from apps.models import *

def create_data(apps, schema_editor):
    BoatService = apps.get_model('apps', 'BoatService')
    BoatService(boat_id=1, guide_id=1, swimlanes_id=1, description= "Service xxx description").save()
    BoatService(boat_id=2, guide_id=2,  swimlanes_id=2, description= "Service xxx description").save()
    BoatService(boat_id=3, guide_id=3,  swimlanes_id=3, description= "Service xxx description").save()
    BoatService(boat_id=4, guide_id=4,  swimlanes_id=4, description= "BoatService 004 description").save()
    BoatService(boat_id=5, guide_id=5,  swimlanes_id=1, description= "BoatService 005 description").save()
    BoatService(boat_id=6, guide_id=6,  swimlanes_id=2, description= "BoatService 006 description").save()
    BoatService(boat_id=7, guide_id=7,  swimlanes_id=3, description= "BoatService 007 description").save()
    BoatService(boat_id=8, guide_id=8,  swimlanes_id=4, description= "BoatService 008 description").save()
    BoatService(boat_id=9, guide_id=9,  swimlanes_id=1, description= "BoatService 009 description").save()
    BoatService(boat_id=10, guide_id=10,  swimlanes_id=2, description= "BoatService 0010 description").save()
    BoatService(boat_id=11, guide_id=11,  swimlanes_id=3, description= "BoatService 0011 description").save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_data_init')
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
